-- テーブルを再作成
DROP TABLE IF EXISTS profiles CASCADE;

CREATE TABLE profiles (
    id bigint generated by default as identity primary key,
    user_id uuid not null unique,
    email text not null,
    name text not null,
    slack_id text,
    class text default 'public',
    inserted_at timestamp with time zone default timezone('Asia/Tokyo'::text, now()) not null,
    updated_at timestamp with time zone default timezone('Asia/Tokyo'::text, now()) not null,
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) 
        REFERENCES auth.users(id) 
        ON DELETE CASCADE
);

-- インデックスを作成
CREATE INDEX ON profiles(user_id);

-- ポリシーを再作成
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own profile"
  ON profiles
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Users can insert own profile"
  ON profiles
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own profile"
  ON profiles
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id);