-- Drop existing table and its dependencies
DROP TABLE IF EXISTS matters CASCADE;

-- Matters table
CREATE TABLE matters (
    id bigint generated by default as identity primary key,
    title text not null,
    category text not null,
    team text not null,
    description text,
    start_date date,
    is_fixed boolean default false,
    is_completed boolean default false,
    total_cost numeric(15,2) default 0,
    cost_count integer default 0,
    total_amount numeric(15,2) default 0,
    business_count integer default 0,
    accounting_memo text,
    unchecked_cost_count integer default 0 not null,
    user_id bigint references profiles(id) on delete cascade not null,
    inserted_at timestamp with time zone default timezone('Asia/Tokyo'::text, now()) not null,
    updated_at timestamp with time zone default timezone('Asia/Tokyo'::text, now()) not null,
    CONSTRAINT fk_matters_profiles 
        FOREIGN KEY (user_id) 
        REFERENCES profiles(id) 
        ON DELETE CASCADE
);

comment on table matters is '案件情報を管理するテーブル';

-- Create index
CREATE INDEX matters_user_id_idx ON matters(user_id);

-- Enable Row Level Security (RLS)
ALTER TABLE matters ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "matters_select_policy" ON matters
    FOR SELECT
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM profiles
            WHERE profiles.id = matters.user_id
            AND profiles.user_id = auth.uid()::uuid
        ) OR 
        EXISTS (
            SELECT 1 FROM profiles
            WHERE profiles.user_id = auth.uid()::uuid
            AND profiles.class IN ('admin', 'accounting')
        ) OR
        EXISTS (
            SELECT 1 FROM profiles
            WHERE profiles.user_id = auth.uid()::uuid
            AND profiles.class = 'teamleader'
            AND profiles.team IS NOT NULL
            AND profiles.team = matters.team
        )
    );

CREATE POLICY "matters_insert_policy" ON matters
    FOR INSERT
    TO authenticated
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM profiles
            WHERE profiles.id = matters.user_id
            AND profiles.user_id = auth.uid()::uuid
        )
    );

CREATE POLICY "matters_update_policy" ON matters
    FOR UPDATE
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM profiles
            WHERE profiles.id = matters.user_id
            AND profiles.user_id = auth.uid()::uuid
        ) OR 
        EXISTS (
            SELECT 1 FROM profiles
            WHERE profiles.user_id = auth.uid()::uuid
            AND profiles.class IN ('admin', 'accounting')
        )
    );

CREATE POLICY "matters_delete_policy" ON matters
    FOR DELETE
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM profiles
            WHERE profiles.id = matters.user_id
            AND profiles.user_id = auth.uid()::uuid
        ) OR 
        EXISTS (
            SELECT 1 FROM profiles
            WHERE profiles.user_id = auth.uid()::uuid
            AND profiles.class = 'admin'
        )
    );

-- Create trigger for updating timestamps
create trigger update_matters_updated_at
    before update on matters
    for each row
    execute procedure update_updated_at_column();

-- Create definition of relationship
COMMENT ON CONSTRAINT matters_user_id_fkey ON matters IS 
  E'@foreignKey (user_id) references profiles (id)
    @manyToOne profiles (id)';
