-- profiles: ユーザー情報
CREATE TABLE profiles (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  email       text NOT NULL,
  name        text NOT NULL,
  slack_id    text,
  class       text DEFAULT 'public',
  team        text,
  inserted_at timestamptz NOT NULL DEFAULT timezone('Asia/Tokyo'::text, now()),
  updated_at  timestamptz NOT NULL DEFAULT timezone('Asia/Tokyo'::text, now())
);

-- matters: 案件情報
CREATE TABLE matters (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title                text NOT NULL,
  category             text NOT NULL,
  team                 text NOT NULL,
  description          text,
  start_date           date,
  is_fixed             boolean DEFAULT false,
  is_completed         boolean DEFAULT false,
  has_updates          boolean DEFAULT false,
  total_cost           numeric(15,2) DEFAULT 0,
  cost_count           integer DEFAULT 0,
  total_amount         numeric(15,2) DEFAULT 0,
  business_count       integer DEFAULT 0,
  accounting_memo      text,
  unchecked_cost_count integer NOT NULL DEFAULT 0,
  user_id              bigint NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  parent_matter_id     bigint REFERENCES matters(id) ON DELETE SET NULL,
  inserted_at          timestamptz NOT NULL DEFAULT timezone('Asia/Tokyo'::text, now()),
  updated_at           timestamptz NOT NULL DEFAULT timezone('Asia/Tokyo'::text, now())
);

-- costs: コスト情報
CREATE TABLE costs (
  id             bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name           text NOT NULL,
  item           text NOT NULL,
  payment_target text NOT NULL,
  price          numeric(15,2) NOT NULL,
  period         date,
  certificate    text NOT NULL,
  withholding    boolean NOT NULL DEFAULT false,
  is_completed   boolean NOT NULL DEFAULT false,
  comment        text,
  matter_id      bigint NOT NULL REFERENCES matters(id) ON DELETE CASCADE,
  inserted_at    timestamptz NOT NULL DEFAULT timezone('Asia/Tokyo'::text, now()),
  updated_at     timestamptz NOT NULL DEFAULT timezone('Asia/Tokyo'::text, now())
);

-- business: 取引先情報
CREATE TABLE business (
  id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name         text NOT NULL,
  invoice_date date,
  period_date  date,
  amount       numeric(15,2),
  is_completed boolean NOT NULL DEFAULT false,
  matter_id    bigint NOT NULL REFERENCES matters(id) ON DELETE CASCADE,
  inserted_at  timestamptz NOT NULL DEFAULT timezone('Asia/Tokyo'::text, now()),
  updated_at   timestamptz NOT NULL DEFAULT timezone('Asia/Tokyo'::text, now())
);

-- select_option_types: 選択肢種類
CREATE TABLE select_option_types (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name          varchar NOT NULL UNIQUE,
  display_name  varchar NOT NULL,
  category      information_category NOT NULL,
  description   text,
  display_order integer DEFAULT 0,
  created_at    timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at    timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

-- select_options: 選択肢値
CREATE TABLE select_options (
  id            serial PRIMARY KEY,
  type_id       uuid REFERENCES select_option_types(id) ON DELETE CASCADE,
  value         varchar NOT NULL,
  display_order integer DEFAULT 0,
  is_active     boolean DEFAULT true,
  created_at    timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at    timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  UNIQUE (type_id, value)
);
